version: '3.8'
services:
  fastapi-app:
    build: ./app
    container_name: fastapi-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
      - ollama
  postgres:
    image: ankane/pgvector
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama serve & sleep 10 && ollama pull mistral && tail -f /dev/null"
volumes:
  pgdata:
  qdrant_data:
  ollama_data:
